import dedent from 'dedent'

import { ACTIVITY_FAMILY_MAP, DEFAULT_WIDGET_FAMILIES, WIDGET_FAMILY_MAP } from '../../../../constants'
import type { ActivityFamily, WidgetConfig } from '../../../../types'

function generateSupplementalFamiliesSwift(families?: ActivityFamily[]): string | null {
  if (!families || families.length === 0) {
    return null
  }
  return families.map((f) => ACTIVITY_FAMILY_MAP[f]).join(', ')
}

function generateVoltraWidgetWrapper(familiesSwift: string): string {
  return dedent`
    // MARK: - Live Activity with Supplemental Families

    struct VoltraWidgetWithSupplementalFamilies: Widget {
      private let wrapped = VoltraWidget()

      var body: some WidgetConfiguration {
        if #available(iOS 18.0, *) {
          return wrapped.body.supplementalActivityFamilies([${familiesSwift}])
        } else {
          return wrapped.body
        }
      }
    }
  `
}

/**
 * Generates Swift code for a single widget struct
 */
function generateWidgetStruct(widget: WidgetConfig): string {
  const families = widget.supportedFamilies ?? DEFAULT_WIDGET_FAMILIES
  const familiesSwift = families.map((f) => WIDGET_FAMILY_MAP[f]).join(', ')

  // Sanitize the widget id for use as a Swift identifier
  const structName = `VoltraWidget_${widget.id}`

  return dedent`
    public struct ${structName}: Widget {
      private let widgetId = "${widget.id}"

      public init() {}

      public var body: some WidgetConfiguration {
        StaticConfiguration(
          kind: "Voltra_Widget_${widget.id}",
          provider: VoltraHomeWidgetProvider(
            widgetId: widgetId,
            initialState: VoltraWidgetInitialStates.getInitialState(for: widgetId)
          )
        ) { entry in
          VoltraHomeWidgetView(entry: entry)
        }
        .configurationDisplayName("${widget.displayName}")
        .description("${widget.description}")
        .supportedFamilies([${familiesSwift}])
        .contentMarginsDisabled()
      }
    }
  `
}

/**
 * Generates the VoltraWidgetBundle.swift file content with configured widgets
 */
export function generateWidgetBundleSwift(widgets: WidgetConfig[], supplementalFamilies?: ActivityFamily[]): string {
  const widgetStructs = widgets.map(generateWidgetStruct).join('\n\n')
  const widgetInstances = widgets.map((w) => `    VoltraWidget_${w.id}()`).join('\n')
  const familiesSwift = generateSupplementalFamiliesSwift(supplementalFamilies)
  const liveActivityWidget = familiesSwift ? 'VoltraWidgetWithSupplementalFamilies()' : 'VoltraWidget()'
  const wrapperStruct = familiesSwift ? '\n\n' + generateVoltraWidgetWrapper(familiesSwift) : ''

  return dedent`
    //
    //  VoltraWidgetBundle.swift
    //
    //  Auto-generated by Voltra config plugin.
    //  This file defines which Voltra widgets are available in your app.
    //

    import SwiftUI
    import WidgetKit
    import VoltraWidget

    @main
    struct VoltraWidgetBundle: WidgetBundle {
      var body: some Widget {
        ${liveActivityWidget}

    ${widgetInstances}
      }
    }

    // MARK: - Home Screen Widget Definitions

    ${widgetStructs}${wrapperStruct}
  `
}

/**
 * Generates the VoltraWidgetBundle.swift file content when no widgets are configured
 * (only Live Activities)
 */
export function generateDefaultWidgetBundleSwift(supplementalFamilies?: ActivityFamily[]): string {
  const familiesSwift = generateSupplementalFamiliesSwift(supplementalFamilies)
  const liveActivityWidget = familiesSwift ? 'VoltraWidgetWithSupplementalFamilies()' : 'VoltraWidget()'
  const wrapperStruct = familiesSwift ? '\n\n' + generateVoltraWidgetWrapper(familiesSwift) : ''

  return dedent`
    //
    //  VoltraWidgetBundle.swift
    //
    //  This file defines which Voltra widgets are available in your app.
    //  You can customize which widgets to include by adding or removing them below.
    //

    import SwiftUI
    import WidgetKit
    import VoltraWidget

    @main
    struct VoltraWidgetBundle: WidgetBundle {
      var body: some Widget {
        ${liveActivityWidget}
      }
    }${wrapperStruct}
  `
}
