import dedent from 'dedent'

import { DEFAULT_WIDGET_FAMILIES, WIDGET_FAMILY_MAP } from '../../../../constants'
import type { ActivityFamily, WidgetConfig } from '../../../../types'

/**
 * Generates Swift code for a single widget struct
 */
function generateWidgetStruct(widget: WidgetConfig): string {
  const families = widget.supportedFamilies ?? DEFAULT_WIDGET_FAMILIES
  const familiesSwift = families.map((f) => WIDGET_FAMILY_MAP[f]).join(', ')

  // Sanitize the widget id for use as a Swift identifier
  const structName = `VoltraWidget_${widget.id}`

  return dedent`
    public struct ${structName}: Widget {
      private let widgetId = "${widget.id}"

      public init() {}

      public var body: some WidgetConfiguration {
        StaticConfiguration(
          kind: "Voltra_Widget_${widget.id}",
          provider: VoltraHomeWidgetProvider(
            widgetId: widgetId,
            initialState: VoltraWidgetInitialStates.getInitialState(for: widgetId)
          )
        ) { entry in
          VoltraHomeWidgetView(entry: entry)
        }
        .configurationDisplayName("${widget.displayName}")
        .description("${widget.description}")
        .supportedFamilies([${familiesSwift}])
        .contentMarginsDisabled()
      }
    }
  `
}

/**
 * Generates the VoltraWidgetBundle.swift file content with configured widgets
 */
export function generateWidgetBundleSwift(
  widgets: WidgetConfig[],
  supplementalActivityFamilies?: ActivityFamily[]
): string {
  // Generate widget structs
  const widgetStructs = widgets.map(generateWidgetStruct).join('\n\n')

  // Generate widget bundle body entries
  const widgetInstances = widgets.map((w) => `    VoltraWidget_${w.id}()`).join('\n')

  return dedent`
    //
    //  VoltraWidgetBundle.swift
    //
    //  Auto-generated by Voltra config plugin.
    //  This file defines which Voltra widgets are available in your app.
    //

    import SwiftUI
    import WidgetKit
    import VoltraWidget

    @main
    struct VoltraWidgetBundle: WidgetBundle {
      var body: some Widget {
        // Standard Live Activity (iPhone-only)
        VoltraWidget()

        // Live Activity with Watch/CarPlay support
        VoltraWidgetWithSupplementalActivityFamilies()

        // Home Screen Widgets
    ${widgetInstances}
      }
    }

    // MARK: - Home Screen Widget Definitions

    ${widgetStructs}
  `
}

/**
 * Generates the VoltraWidgetBundle.swift file content when no widgets are configured
 * (only Live Activities)
 */
export function generateDefaultWidgetBundleSwift(supplementalActivityFamilies?: ActivityFamily[]): string {
  return dedent`
    //
    //  VoltraWidgetBundle.swift
    //
    //  This file defines which Voltra widgets are available in your app.
    //  You can customize which widgets to include by adding or removing them below.
    //

    import SwiftUI
    import WidgetKit
    import VoltraWidget  // Import Voltra widgets

    @main
    struct VoltraWidgetBundle: WidgetBundle {
      var body: some Widget {
        // Standard Live Activity (iPhone-only)
        VoltraWidget()

        // Live Activity with Watch/CarPlay support
        VoltraWidgetWithSupplementalActivityFamilies()
      }
    }
  `
}
