import fs from 'node:fs'
import path from 'node:path'

import { ConfigPlugin, withPodfile as withExpoPodfile } from '@expo/config-plugins'

const packageJson = fs.readFileSync(path.join(__dirname, '..', '..', '..', '..', '..', 'package.json'), 'utf8')
const libraryName = JSON.parse(packageJson).name

/**
 * Generates the Podfile target content for the widget extension.
 */
function getTargetContent(targetName: string): string {
  const backtick = '`'
  return `
# Voltra Widget Extension Target
# DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED BY THE VOLTRA PLUGIN
target '${targetName}' do
  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  require 'json'
  project_root = "#{Pod::Config.instance.installation_root}/.."
  voltra_module = JSON.parse(${backtick}npx expo-modules-autolinking search -p apple --json --project-root #{project_root}${backtick})
  podspec_dir_path = Pathname.new(File.join(voltra_module['${libraryName}']['path'], 'ios')).relative_path_from(Pathname.new(__dir__)).to_path
  
  pod 'VoltraWidget', :path => podspec_dir_path
end`
}

export interface ConfigurePodfileProps {
  targetName: string
}

/**
 * Plugin step that adds the Podfile target for the widget extension.
 */
export const configurePodfile: ConfigPlugin<ConfigurePodfileProps> = (config, { targetName }) => {
  return withExpoPodfile(config, (podfile) => {
    const targetContent = getTargetContent(targetName)

    // Check if target already exists (avoid duplicates)
    const targetMarker = "target '" + targetName + "'"
    if (podfile.modResults.contents.includes(targetMarker)) {
      return podfile
    }

    podfile.modResults.contents = podfile.modResults.contents + '\n' + targetContent
    return podfile
  })
}
