import { ConfigPlugin, withPodfile as withExpoPodfile } from '@expo/config-plugins'

const getTargetContent = (targetName: string) => {
  const backtick = '`'
  return `
# Voltra Widget Extension Target
# DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED BY THE VOLTRA PLUGIN
target '${targetName}' do
  require 'json'
  project_root = "#{Pod::Config.instance.installation_root}/.."
  voltra_module = JSON.parse(${backtick}npx expo-modules-autolinking search voltra -p apple --json --project-root #{project_root}${backtick})
  podspec_dir_path = Pathname.new(File.join(voltra_module['voltra']['path'], 'ios')).relative_path_from(Pathname.new(__dir__)).to_path
  
  pod 'Voltra/Widget', :path => podspec_dir_path
end`
}

export const withPodfile: ConfigPlugin<{
  targetName: string
}> = (config, { targetName }) => {
  return withExpoPodfile(config, (podfile) => {
    const targetContent = getTargetContent(targetName)

    // Check if target already exists (avoid duplicates)
    const targetMarker = 'target ' + "'" + targetName + "'"
    if (podfile.modResults.contents.includes(targetMarker)) {
      return podfile
    }

    podfile.modResults.contents = podfile.modResults.contents + '\n' + targetContent
    return podfile
  })
}
