import type { WidgetConfig, WidgetFamily } from '../types'

/**
 * Maps JS widget family names to SwiftUI WidgetFamily enum cases
 */
const FAMILY_MAP: Record<WidgetFamily, string> = {
  systemSmall: '.systemSmall',
  systemMedium: '.systemMedium',
  systemLarge: '.systemLarge',
  systemExtraLarge: '.systemExtraLarge',
  accessoryCircular: '.accessoryCircular',
  accessoryRectangular: '.accessoryRectangular',
  accessoryInline: '.accessoryInline',
}

/**
 * Generates Swift code for a single widget struct
 */
function generateWidgetStruct(widget: WidgetConfig): string {
  const families = widget.supportedFamilies ?? ['systemSmall', 'systemMedium', 'systemLarge']
  const familiesSwift = families.map((f) => FAMILY_MAP[f]).join(', ')

  // Sanitize the widget id for use as a Swift identifier
  const structName = `VoltraWidget_${widget.id}`

  return `
public struct ${structName}: Widget {
  private let widgetId = "${widget.id}"

  public init() {}
  
  public var body: some WidgetConfiguration {
    StaticConfiguration(kind: "Voltra_Widget_${widget.id}", provider: VoltraHomeWidgetProvider(widgetId: widgetId, initialState: VoltraWidgetInitialStates.getInitialState(for: widgetId))) { entry in
      VoltraHomeWidgetView(entry: entry)
    }
    .configurationDisplayName("${widget.displayName}")
    .description("${widget.description}")
    .supportedFamilies([${familiesSwift}])
    .contentMarginsDisabled()
  }
}`
}

/**
 * Generates the VoltraWidgetBundle.swift file content
 */
export function generateWidgetBundleSwift(widgets: WidgetConfig[]): string {
  // Generate widget structs
  const widgetStructs = widgets.map(generateWidgetStruct).join('\n')

  // Generate widget bundle body entries
  const widgetInstances = widgets.map((w) => `    VoltraWidget_${w.id}()`).join('\n')

  return `//
//  VoltraWidgetBundle.swift
//
//  Auto-generated by Voltra config plugin.
//  This file defines which Voltra widgets are available in your app.
//

import SwiftUI
import WidgetKit
import Voltra

@main
struct VoltraWidgetBundle: WidgetBundle {
  var body: some Widget {
    // Live Activity Widget (Dynamic Island + Lock Screen)
    VoltraWidget()
    
    // Home Screen Widgets
${widgetInstances}
  }
}

// MARK: - Home Screen Widget Definitions
${widgetStructs}
`
}

/**
 * Generates the VoltraWidgetBundle.swift file content when no widgets are configured
 * (only Live Activities)
 */
export function generateDefaultWidgetBundleSwift(): string {
  return `//
//  VoltraWidgetBundle.swift
//
//  This file defines which Voltra widgets are available in your app.
//  You can customize which widgets to include by adding or removing them below.
//

import SwiftUI
import WidgetKit
import Voltra  // Import Voltra widgets

@main
struct VoltraWidgetBundle: WidgetBundle {
  var body: some Widget {
    // Live Activity Widget (Dynamic Island + Lock Screen)
    VoltraWidget()
  }
}
`
}
